trigger:
  branches:
    include:
      - master
  paths:
    include:
      - packages/eslint-config-node/*

pool:
  vmImage: 'ubuntu-latest'
  demands: npm

stages:
  - stage: Publish
    displayName: Publish library
    jobs:
      - job:
        displayName: Publish
        steps:
          - script: |
              npm publish -w @polymath_labs/eslint-config-node
            displayName: "npm publish"
